### ISSUE TITLE
Stage of development

### ISSUE THREAD

**Issue by comendantmc** [WorldQL/mammoth#11]
Hi, I just wondering on which stage the development is right now? Is it still being developed? Can I use it in the current state?

**Comment by Jaxkr** [comment]
Working on a roadmap, will close this issue once it’s published.

**Comment by simon-evilinc-dk** [comment]
This is amazing, and very needed in the gaming world. Imagine Valheim with this backend.

**Comment by blacksythe** [comment]
Looking forward to your roadmap and record attempt. Id be interested if this ever supported forge or fabric

**Comment by walksanatora** [comment]
main problem with forge/fabric support is all of the possible interactions between blocks
although once it is released i will try some mods to see how well they work via [magma](https://magmafoundation.org/) because it may work better than expected
and with low expectations comes the chance for them to be blown out of the water

**Comment by ChengxiX** [comment]
Yes, please consider minecraft server with mods.

**Comment by Jaxkr** [comment]
https://www.worldql.com/posts/2021-09-mammoth-development-roadmap/

**Comment by Jaxkr** [comment]
https://www.worldql.com/posts/2021-09-mammoth-development-roadmap/
